### ISSUE TITLE
can't load 'planner.goal_plan' and can't find 'fig/trajectory/good_maze_rollout.pkl'

### ISSUE THREAD

**Issue by Roythuly** [SiyuanLee/HESS#1]
Thank you for your repo! When I try this project, I find some problem which needs your help.

1. In hier_sac.py, 'from planner.goal_plan import *', I search the goal_plan module for the whole project, but it may not exist in this repo.
![image](https://user-images.githubusercontent.com/57201828/160979321-b69a7310-6d11-47a6-89dc-504ed1712e1c.png)

2. If I comment 'from planner.goal_plan import *', it can not find the file 'good_maze_rollout.pkl' in the line 56 in 'hier_sac.py'.
![image](https://user-images.githubusercontent.com/57201828/160979411-470069da-bb33-4fa3-b251-af5cfc371f98.png)

That's all! Thank you!

(python train_hier_sac.py --c 50 --abs_range 20  --env-name AntMaze1Test-v1 --test AntMaze1Test-v1 \
--weight_decay 1e-5 --device cuda:1 --seed 2)

**Comment by momofive** [comment]
I met the same problem as Roythuly, hmm. Looking forward to your precious reply!!!

**Comment by SiyuanLee** [comment]
The code has been cleaned. Try it now :)
