### ISSUE TITLE
Pytorch Version

### ISSUE THREAD

**Issue by NoListen** [SiyuanLee/HESS#2]
Hi, firstly, thank you for kindly sharing the codes.

I met a problem when I ran the experiments on non-image-based Ant-Maze.

When I use Pytorch 1.4, the reported error is `ModuleNotFoundError: No module named 'torch.nn.utils.prune'`

When I use Pytorch 1.6 & 1.7, the reported error is 

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of TBackward, is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

which I found was caused by these [codes](https://github.com/SiyuanLee/HESS/blob/3d95687e55b040766128aaf090539d901da2f694/algos/sac/sac.py#L118-L128)  as the corresponding inputs for those losses have been changed.

```
        self.critic_optim.zero_grad()
        qf1_loss.backward()
        self.critic_optim.step()

        self.critic_optim.zero_grad()
        qf2_loss.backward()
        self.critic_optim.step()

        self.policy_optim.zero_grad()
        policy_loss.backward()
        self.policy_optim.step()
```

When I merge them into a total_loss

```
        total_loss = qf1_loss + qf2_loss + policy_loss
        self.critic_optim.zero_grad()
        total_loss.backward()
        self.critic_optim.step()
```

I got a poorer result than yours which only covers 0.38 area at around 850 * 1000 = 0.85M steps so I do not believe it can reach the goal at 1M steps and just paused it

![HESS](https://user-images.githubusercontent.com/6292016/168184363-154a6ae6-0483-4e9d-88a2-e791563398a3.png)

Could you help with this issue?

**Comment by SiyuanLee** [comment]
Hi! Thx for your interest in our work. The PyTorch version should be 1.4.0, and the 'prune' function is never used, so I have commented it out in the latest version. Pls check the new code now :)
